version: 6.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore
  
build:
  project: Migrator.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.dll
    name: DotNetProjects.Migrator.dll
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.pdb
    name: DotNetProjects.Migrator.pdb
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.Framework.dll
    name: DotNetProjects.Migrator.Framework.dll
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.Framework.pdb
    name: DotNetProjects.Migrator.Framework.pdb
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.Providers.dll
    name: DotNetProjects.Migrator.Providers.dll
  - path: src\Migrator\bin\Release\net40\DotNetProjects.Migrator.Providers.pdb
    name: DotNetProjects.Migrator.Providers.pdb
  - path: '**\DotNetProjects.Migrator*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  